name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

    - name: Vale
      uses: errata-ai/vale-action@ff9447943c1cad0f45649b630e29112511f80e5a # master
      with:
        # Optional
        # styles: |
        #   https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
        #   https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip

        # Optional
        config: https://raw.githubusercontent.com/segmentio/segment-docs/develop/.vale.ini

        # Optional
        files: __onlyModified
        onlyAnnotateModifiedLines: true
      env:
        # Required, set by GitHub actions automatically:
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
