name: Repo Sync

on:
  schedule: 
  - cron: "*/30 * * * *" # every 30 minutes.

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    
    - uses: repo-sync/github-sync@3832fe8e2be32372e1b3970bbae8e7079edeec88 # v2.3.0
      name: Sync repo to branch
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_REPO_SCOPE }}
      with:
        source_repo: ${{ secrets.SOURCE_REPO }}
        source_branch: ${{ secrets.SOURCE_BRANCH }}
        destination_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
        github_token: ${{ secrets.DOCS_BOT_PAT_REPO_SCOPE }}
    
    - uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5 # v2.12.1
      name: Create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_REPO_SCOPE }}
      with:
        source_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
        destination_branch: ${{ secrets.DESTINATION_BRANCH }}
        pr_title: 'repo sync'
        pr_body: "This is an automated pull request to sync changes between the public and private repos.\n\n:robot: This pull request should be merged (not squashed) to preserve continuity across repos, so please let a bot do the merging!"
        pr_label: autoupdate,automated-reposync-pr
        github_token: ${{ secrets.DOCS_BOT_PAT_REPO_SCOPE }}

    - name: Find pull request
      uses: juliangruber/find-pull-request-action@92b38d91ef26fd0f47374257f50e78432359a45f # v1.11.1
      id: find-pull-request
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: repo-sync
        base: ${{ secrets.DESTINATION_BRANCH }}
        author: bot-docsteam 
        state: open

    - name: Approve pull request
      if: ${{ steps.find-pull-request.outputs.number }}
      uses: juliangruber/approve-pull-request-action@f83b836abaed1b3ab639ae61f9117c52ae405f65 # v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.find-pull-request.outputs.number }}
    
    - name: Merge Pull Request
      if: ${{ steps.find-pull-request.outputs.number }}
      uses: juliangruber/merge-pull-request-action@8325c6102b479a25200b2ecbede066b1ac3e2feb # v1.4.0
      with:
        github-token: ${{ secrets.DOCS_BOT_PAT_REPO_SCOPE }}
        number: ${{ steps.find-pull-request.outputs.number }}
        method: merge
